package com.test.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-03-27T11:17:56.371+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://service.test.com/", name = "GetData")
@XmlSeeAlso({ObjectFactory.class})
public interface GetData {

    @WebMethod
    @RequestWrapper(localName = "getData", targetNamespace = "http://service.test.com/", className = "com.test.service.GetData_Type")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.test.com/", className = "com.test.service.GetDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getData();

    @WebMethod
    @RequestWrapper(localName = "parseXML", targetNamespace = "http://service.test.com/", className = "com.test.service.ParseXML")
    @ResponseWrapper(localName = "parseXMLResponse", targetNamespace = "http://service.test.com/", className = "com.test.service.ParseXMLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String parseXML(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "transferXML", targetNamespace = "http://service.test.com/", className = "com.test.service.TransferXML")
    @ResponseWrapper(localName = "transferXMLResponse", targetNamespace = "http://service.test.com/", className = "com.test.service.TransferXMLResponse")
    public void transferXML(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
