package com.test.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-03-27T11:17:56.414+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "GetDataImplService", 
                  wsdlLocation = "http://localhost/GetDataService/WS/getDataWS?wsdl",
                  targetNamespace = "http://service.test.com/") 
public class GetDataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.test.com/", "GetDataImplService");
    public final static QName GetDataImplPort = new QName("http://service.test.com/", "GetDataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/GetDataService/WS/getDataWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetDataImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/GetDataService/WS/getDataWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetDataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetDataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GetDataImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetDataImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetDataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetData
     */
    @WebEndpoint(name = "GetDataImplPort")
    public GetData getGetDataImplPort() {
        return super.getPort(GetDataImplPort, GetData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetData
     */
    @WebEndpoint(name = "GetDataImplPort")
    public GetData getGetDataImplPort(WebServiceFeature... features) {
        return super.getPort(GetDataImplPort, GetData.class, features);
    }

}
